Injector:
  ProviderFactory:
    class: 'Bigfork\SilverStripeOAuth\Client\Factory\ProviderFactory'
    properties:
      providers: []
Member:
  extensions:
    - Bigfork\SilverStripeOAuth\Client\Extension\MemberExtension
